# Generated by Django 3.0.5 on 2023-01-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221222_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(through='api.GenreTitle', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title'),
        ),
    ]
