# Generated by Django 3.0.5 on 2023-01-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230111_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Genre'),
        ),
    ]
