# Generated by Django 3.0.5 on 2023-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230119_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='token',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не получил токен'), (1, 'Получил токен')], default=0),
        ),
    ]
