# Generated by Django 3.0.5 on 2023-01-22 08:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_confirmationcode_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=50, validators=[api.validators.role_validator]),
        ),
    ]
