# Generated by Django 3.0.5 on 2023-01-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230122_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='titles', to='api.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'year')},
        ),
    ]
