# Generated by Django 3.0.5 on 2023-01-22 09:05

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(validators=[api.validators.ascii_validator]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(validators=[api.validators.ascii_validator]),
        ),
    ]
