# Generated by Django 3.0.5 on 2023-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230123_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не получил токен'), (1, 'Получил токен')], default=0),
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
