# Generated by Django 3.0.5 on 2023-02-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set(),
        ),
    ]
